In [15]:
#Exercise
#Use the dataset of Game, we have explored earlier and perform following operations.
#
#Calculate the total global sales for all games in the dataset.
#Find the game with the highest global sales.
#Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
#Find the top 5 most popular game genres based on global sales.
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
#Display last 10 rows.
#Determine the top 3 gaming platforms with the highest global sales.
#Calculate the market share (percentage of global sales) for each genre.
#Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)


import pandas as pd



df = pd.read_csv("/content/vgsalesGlobale.csv")

df.head()



Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [29]:
# 1.global sales for all games

total_global_sales = df["Global_Sales"].sum()

# 2.  highest global sales

highest_selling_game = df.loc[df["Global_Sales"].idxmax(), ["Name", "Global_Sales"]]

# 3.  average sales for each region

average_sales_by_region = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].mean()

# 4. top 5 most popular game genres based on global sales

top_5_genres = df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(5)

# 5. total sales for each genre in each region and most popular genre in NA

sales_by_genre_region = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
most_popular_genre_na = sales_by_genre_region["NA_Sales"].idxmax()

# 6. Display the last 10 rows of the dataset

last_10_rows = df.tail(10)


In [30]:

# 7. Determine the top 3 gaming platforms with the highest global sales

top_3_platforms = df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(3)

# 8. Calculate the market share for each genre

market_share_by_genre = (df.groupby("Genre")["Global_Sales"].sum() / total_global_sales) * 100

# 9. Calculate the correlation coefficient between NA_Sales and EU_Sales

correlation_na_eu = df["NA_Sales"].corr(df["EU_Sales"])

# Print results

print("Global Sales:", total_global_sales)
print("\nhighest Selling Game is :\n", highest_selling_game)
print("\naverage Sales by Region:\n", average_sales_by_region)
print("\n5 Most Popular Genres are :\n", top_5_genres)
print("\Popular Genre in NA is :", most_popular_genre_na)
print("\nTop 3 Gaming Platforms:\n", top_3_platforms)
print("\nmarket Share by Genre:\n", market_share_by_genre)
print("\ncorrelation between NA Sales and EU Sales:", correlation_na_eu)

print("\nlast 10 Rows :")
print(last_10_rows)


Total Global Sales: 8920.44

Highest Selling Game:
 Name            Wii Sports
Global_Sales         82.74
Name: 0, dtype: object

Average Sales by Region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

Top 5 Most Popular Genres:
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

Most Popular Genre in NA: Action

Top 3 Gaming Platforms:
 Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

Market Share by Genre:
 Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

Correlation 

In [18]:

english_to_spanish = {
    "hey": "oa",
    "world": "mundo",
    "Thank you!": "¡Gracias!",
    "please": "por favor",
    "You're welcome!": "De nada",
    "no": "no",
    "Excuse me": "Disculpe!",
    "water": "agua",
    "friend": "amigo",
}

while True:

    word = input("pleis enter an english word or type 'exit' to quit : ").lower()


    if word == "exit":
        print("Goodbye, have a nice day : ) !")
        break



    if word in english_to_spanish:

        print(f"The spanish translation for '{word}' is '{english_to_spanish[word]}'.")
    else:
        print(f"The translation for '{word}' does not exist.")


pleis enter an english word or type 'exit' to quit : hey
The spanish translation for 'hey' is 'oa'.
pleis enter an english word or type 'exit' to quit : exit
Goodbye, have a nice day : ) !


In [31]:
def classify_emails(emails):


    important_emails = []
    promotional_emails = []
    spam_emails = []


    important_keywords = ["meeting", "urgent", "deadline", "project", "schedule"]
    promotion_keywords = ["sale", "discount", "offer", "deal", "promo"]
    spam_keywords = ["win", "free", "lottery", "prize", "click here"]


    for email in emails:
        email_lower = email.lower()

        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)

        elif any(keyword in email_lower for keyword in promotion_keywords):
            promotional_emails.append(email)

        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)

        else:

            pass

    return important_emails, promotional_emails, spam_emails

emails = [
    "project deadline is approaching",
    "huge discount on your favorite items",
    "you won a free prize! Click here to claim",
    "meeting scheduled for tomorrow",
    "exclusive deal just for you",
    "congratulations, you are a lottery winner!"
]

important, promotions, spam = classify_emails(emails)

print("Important Emails:", important)
print("Promotional Emails:", promotions)
print("Spam Emails:", spam)


Important Emails: ['project deadline is approaching', 'meeting scheduled for tomorrow']
Promotional Emails: ['huge discount on your favorite items', 'exclusive deal just for you']
Spam Emails: ['you won a free prize! Click here to claim', 'congratulations, you are a lottery winner!']


In [21]:
def online_store():

    shopping_cart = []

    products = {

        1: "AI Response Simulator",
        2: "Investment Decision",
        3: "Data Analytics Toolkit"
    }

    print("Welcome to the Laiba's Online Store!")
    print("The available products for you :D :")

    for key, value in products.items():
        print(f"{key}. {value}")
    print("Type 'q' to quit and proceed to checkout.")

    while True:
        choice = input("Enter the number corresponding to the product you want to add to your cart (or 'q' to checkout): ").lower()

        if choice == 'q':
            print("Checking out")
            break

        if choice.isdigit():
            choice = int(choice)
            if choice in products:
                shopping_cart.append(products[choice])
                print(f"Added '{products[choice]}' to your shopping cart.")
            else:
                print("Plieas select a valid product from the given ones.")
        else:
            print("Please enter a number or 'q' to quit.")

    if shopping_cart:
        print("\n")
        print("Your shopping cart contains:")
        for item in shopping_cart:
            print(f"- {item}")
    else:
        print("\n your shopping cart is empty :(")

    print("\nThank you for shopping with us. Goodbye, see you next time!")

online_store()

Welcome to the Laiba's Online Store!
The available products for you :D :
1. AI Response Simulator
2. Investment Decision
3. Data Analytics Toolkit
Type 'q' to quit and proceed to checkout.
Enter the number corresponding to the product you want to add to your cart (or 'q' to checkout): 1
Added 'AI Response Simulator' to your shopping cart.
Enter the number corresponding to the product you want to add to your cart (or 'q' to checkout): 2
Added 'Investment Decision' to your shopping cart.
Enter the number corresponding to the product you want to add to your cart (or 'q' to checkout): q
Checking out


Your shopping cart contains:
- AI Response Simulator
- Investment Decision

Thank you for shopping with us. Goodbye, see you next time!


In [22]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

addition_result = arr1 + arr2
product_result = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print(" addition Result:", addition_result)
print("prroduct Result:", product_result)


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]
Element wise Addition Result: [11 22 33 44 55]
Element wise Product Result: [ 10  40  90 160 250]


In [24]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array_2d = array_1d.reshape(3, 4)

array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[7, 8, 9], [10, 11, 12]])

horizontal_concat = np.hstack((array_a, array_b)) #h
vertical_concat = np.vstack((array_a, array_b))#v

print(" 1D Array:", array_1d)
print("Reshape 2D Array :\n", array_2d)
print("Array A:\n", array_a)
print("Array B:\n", array_b)
print("Horizontally Concatenated Array:\n", horizontal_concat)
print("Vertically Concatenated Array:\n", vertical_concat)

 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape 2D Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array A:
 [[1 2 3]
 [4 5 6]]
Array B:
 [[ 7  8  9]
 [10 11 12]]
Horizontally Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically Concatenated Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:


list_o = [1, 2, 3, 4, 5]
reversed_list = list_o[::-1]

print("Original List:", list_o)
print("Reversed List:", reversed_list)


Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]
